name: build

on:
  push:
    branches:
      - cygwin
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: install go
        uses: actions/setup-go@v3
        with:
          go-version: '1.19.2'

      - name: prep cygwin
        uses: cygwin/cygwin-install-action@master
        with:
          packages: |
            binutils, gcc-core, gcc-g++, patch, libpcre2-devel, python3, python3-devel,
            wget, ninja, git, perl, cmake, libprotobuf-devel, libbrotli-devel,
            libzstd-devel, liblz4-devel, zlib-devel

      # required for patches
      - name: git config
        env:
          SHELLOPTS: igncr
          CHERE_INVOKING: 1
        shell: C:\cygwin\bin\bash.exe -eo pipefail '{0}'
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          git config --global core.autocrlf input
          git config --global --add safe.directory $(cygpath -u "${{ github.workspace }}")
          for repo in $(cat .gitmodules | grep -E "path = .+" | gawk '{ print $3 }'); do
              git config --global --add safe.directory $(cygpath -u "${{ github.workspace }}/${repo}")
          done

      - name: build googletest
        env:
          SHELLOPTS: igncr
        shell: C:\cygwin\bin\bash.exe -eo pipefail '{0}'
        run: |
          wget https://github.com/google/googletest/archive/refs/tags/release-1.12.1.tar.gz \
               -O googletest-release-1.12.1.tar.gz
          tar xf googletest-release-1.12.1.tar.gz
          cd googletest-release-1.12.1
          cmake -B build -G Ninja \
                -DCMAKE_BUILD_TYPE=Release \
                -DCMAKE_INSTALL_PREFIX=/usr \
                -DCMAKE_INSTALL_LIBDIR=lib \
                -DBUILD_SHARED_LIBS=ON \
                -DPYTHON_EXECUTABLE=python3 \
                -Dgtest_build_tests=OFF \
                -DBUILD_GMOCK=ON
          cmake --build build
          find build -name '*.pump' -print -delete
          cmake --build build --target install

      - name: build & install
        env:
          SHELLOPTS: igncr
          CHERE_INVOKING: 1
        shell: C:\cygwin\bin\bash.exe -eo pipefail '{0}'
        run: |
          cmake -B build -G Ninja \
                -DCMAKE_INSTALL_PREFIX=/usr \
                -DCMAKE_INSTALL_LIBDIR=lib \
                -DCMAKE_BUILD_TYPE=Release
          cmake --build build
          echo -e "\n### make install ###\n"
          DESTDIR=dists cmake --install build
          tar czf dists.tar.gz dists
          echo -e "\n### all done ###\n"

      - name: upload dists
        uses: actions/upload-artifact@v3
        with:
          name: dists
          path: ${{ github.workspace }}/dists.tar.gz
